## Numpy Tutorial

In [6]:
## initially lets import the numpy

import numpy as np

In [7]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [8]:
type(arr)

numpy.ndarray

In [10]:
arr

array([1, 2, 3, 4, 5])

In [11]:
print(arr)

[1 2 3 4 5]


In [12]:
arr.shape

(5,)

In [13]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,8,6,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [14]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 8, 6, 9]])

In [15]:
arr.shape

(3, 5)

In [16]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [8, 6, 9]])

In [17]:
arr.reshape(3,8)

ValueError: cannot reshape array of size 15 into shape (3,8)

In [18]:
## Indexing
arr=np.array([1,2,3,4,5,6,7,8,9])

In [19]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[3]

4

In [22]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,8,6,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [23]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 8, 6, 9]])

In [24]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 8, 6, 9]])

In [25]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [26]:
arr[2:,2:]

array([[8, 6, 9]])

In [27]:
arr[1:,3:]

array([[5, 6],
       [6, 9]])

In [29]:
arr[1:,2:4]

array([[4, 5],
       [8, 6]])

In [31]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [36]:
arr=np.arange(0,10,step=2)

In [37]:
arr

array([0, 2, 4, 6, 8])

In [38]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [39]:
## copy() function and broadcasting
arr

array([0, 2, 4, 6, 8])

In [40]:
arr[3:]=100

In [41]:
arr

array([  0,   2,   4, 100, 100])

In [42]:
arr

array([  0,   2,   4, 100, 100])

In [43]:
arr1=arr

In [44]:
arr1

array([  0,   2,   4, 100, 100])

In [46]:
arr1=arr.copy()

In [47]:
print(arr)
arr1[3:]=1000
print(arr1)

[  0   2   4 100 100]
[   0    2    4 1000 1000]


In [62]:
arr

[1, 2, 3, 4, 5]

In [63]:
arr

[1, 2, 3, 4, 5]

In [64]:
## Some conditions very useful in exploratory data analysis.

val=3

arr<2

TypeError: '<' not supported between instances of 'list' and 'int'

In [65]:
arr=np.arange(0,10,step=2)

In [66]:
arr

array([0, 2, 4, 6, 8])

In [67]:
val=2
arr<2

array([ True, False, False, False, False])

In [68]:
arr*2

array([ 0,  4,  8, 12, 16])

In [69]:
arr/2

array([0., 1., 2., 3., 4.])

In [70]:
arr%2

array([0, 0, 0, 0, 0], dtype=int32)

In [71]:
arr[arr<2]

array([0])

In [72]:
arr[arr<300]

array([0, 2, 4, 6, 8])

In [74]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [77]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
np.random.rand(3,3)

array([[0.03509966, 0.80743089, 0.50307267],
       [0.92132184, 0.30005278, 0.97523393],
       [0.22901997, 0.74897347, 0.50642095]])